spring:
  datasource:
    username: postgtes
    password: Tsunami9
    driverClassName: org.postgresql.Driver
    driverDialect: org.hibernate.dialect.PostgreSQL82Dialect
    url: jdbc:postgresql://localhost/chat_service_db
  jpa:
    hibernate:
      ddl-auto: validate



server:
  port: 8087

redis:
  host: 10.0.0.1